set -e

go install github.com/barnex/godoc2ghmd
out=godoc.md
pre=github.com/barnex/bruteray/
cmd='godoc2ghmd -ex'

cp main.md $out

for pkg in br shape mat light transf; do
	echo >> $out; echo >> $out
	$cmd $pre/$pkg >> $out
	#$cmd $pre/$pkg | sed 's-doc/Example-../doc/Example-g' > $pkg/README.md
	$cmd $pre/$pkg > $pkg/README.md
done


echo >> $out
echo >> $out
echo "- - -" >> $out
echo 'Generated by a modified [godoc2ghmd](https://github.com/GandalfUK/godoc2ghmd)' >> $out
